--- # Configuration
extraction:
  enabled: true
  api: instagram
  api_cfg:
    ACCESS_TOKEN : YOUR_TOKEN
    ACCESS_SECRET : YOUR_SECRET_KEY
    CONSUMER_KEY : CONSUMER_KEY
    CONSUMER_SECRET : CONSUMER_SECRET
    frequency: ../resources/frequs.json
  location:
    lat: 46.205850
    lon: 6.157521
    radius: 1
  number: 1000
  pipeline:
    Babel: false
    WordNet: true
  storage:
    module: DB
    module_cfg:
      path: sqlite:///database/output.db
classification:
  enabled: true
  inputdb: sqlite:///database/output.db
  ontology_path: resources
  ontology: kr-owlxml.owl
  ontology_name: http://tagis.kr.com
  result_ontology: data/results.owl
  outputdb: sqlite:///database/output-classified.db
